# Form implementation generated from reading ui file '.\connect_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 232)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(36)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.hostname = QtWidgets.QLineEdit(Form)
        self.hostname.setObjectName("Hostname")
        self.gridLayout.addWidget(self.hostname, 0, 1, 1, 1)
        self.aliasLabel = QtWidgets.QLabel(Form)
        self.aliasLabel.setObjectName("aliasLabel")
        self.gridLayout.addWidget(self.aliasLabel, 1, 0, 1, 1)
        self.alias = QtWidgets.QLineEdit(Form)
        self.alias.setObjectName("Alias")
        self.gridLayout.addWidget(self.alias, 1, 1, 1, 1)
        self.port = QtWidgets.QLineEdit(Form)
        self.port.setObjectName("Port")
        self.gridLayout.addWidget(self.port, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.connect = QtWidgets.QPushButton(Form)
        self.connect.setObjectName("Connect")
        self.horizontalLayout_2.addWidget(self.connect)
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setObjectName("Cancel")
        self.horizontalLayout_2.addWidget(self.cancel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Connect"))
        self.label.setText(_translate("Form", "Hostname"))
        self.aliasLabel.setText(_translate("Form", "Alias"))
        self.label_2.setText(_translate("Form", "Port Number"))
        self.connect.setText(_translate("Form", "Connect"))
        self.cancel.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
