# Form implementation generated from reading ui file 'connect_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 232)
        Form.setStyleSheet("background: #fff;")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(18)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.port = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.port.setFont(font)
        self.port.setStyleSheet("#port {\n"
"    background-color: #fafafa;\n"
"    border: 1px solid transparent;\n"
"    border-bottom-color: #ccc;\n"
"    padding: .2em;\n"
"    margin-bottom: 1px;\n"
"}\n"
"#port:focus {\n"
"    border-bottom-color: #64d2ff;\n"
"    border-width: 2px;\n"
"}")
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 1, 1, 1, 1)
        self.username = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setStyleSheet("#username {\n"
"    background-color: #fafafa;\n"
"    border: 1px solid transparent;\n"
"    border-bottom-color: #ccc;\n"
"    padding: .2em;\n"
"    margin-bottom: 1px;\n"
"}\n"
"#username:focus {\n"
"    border-bottom-color: #64d2ff;\n"
"    border-width: 2px;\n"
"}")
        self.username.setObjectName("username")
        self.gridLayout.addWidget(self.username, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.hostname = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hostname.setFont(font)
        self.hostname.setStyleSheet("#hostname {\n"
"    background-color: #fafafa;\n"
"    border: 1px solid transparent;\n"
"    border-bottom-color: #ccc;\n"
"    padding: .2em;\n"
"    margin-bottom: 1px;\n"
"}\n"
"#hostname:focus {\n"
"    border-bottom-color: #64d2ff;\n"
"    border-width: 2px;\n"
"}")
        self.hostname.setObjectName("hostname")
        self.gridLayout.addWidget(self.hostname, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.connect = QtWidgets.QPushButton(Form)
        self.connect.setStyleSheet("#connect {\n"
"    border: 1px solid #30d158;\n"
"    border-radius: .3em;\n"
"    padding: .2em .5em;\n"
"    min-width: 4em;\n"
"}\n"
"#connect:hover {\n"
"    background-color: #30d158;\n"
"    color: #fff;\n"
"}")
        self.connect.setObjectName("connect")
        self.horizontalLayout.addWidget(self.connect)
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setStyleSheet("#cancel {\n"
"    border: 1px solid #ff375f;\n"
"    border-radius: .3em;\n"
"    padding: .2em .5em;\n"
"    min-width: 4em;\n"
"}\n"
"#cancel:hover {\n"
"    background-color: #ff375f;\n"
"    color: #fff;\n"
"    padding-left: 0;\n"
"}")
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.connect.clicked.connect(self.connectClicked)
        self.cancel.clicked.connect(self.cancelClicked)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def connectClicked(self, Form):
        print("Connect Clicked")

    def cancelClicked(self, Form):
        print("Cancel Clicked")
        sys.exit()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "QtChat - Connect"))
        self.label_2.setText(_translate("Form", "Port Number"))
        self.label_3.setText(_translate("Form", "Username"))
        self.label.setText(_translate("Form", "Hostname"))
        self.connect.setText(_translate("Form", "Connect"))
        self.cancel.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
