# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMouseTracking(False)
        MainWindow.setWindowOpacity(0.96)
        MainWindow.setStyleSheet("background: #fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.channel = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.channel.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.channel.setFont(font)
        self.channel.setStyleSheet("#channel {\n"
"    border: none;\n"
"    font-size: 9;\n"
"    border-right: 1px solid #d6d9dc;\n"
"    padding: .2em 0;\n"
"}\n"
"#channel::item {\n"
"    background: #f2f2f7;\n"
"    border-radius: .3em;\n"
"    margin-right: .3em;\n"
"    padding: 0 .2em;\n"
"}\n"
"#channel::item:selected {\n"
"    background-color: #64d2ff;\n"
"    color: #fff;\n"
"}")
        self.channel.setObjectName("channel")
        item = QtWidgets.QListWidgetItem()
        self.channel.addItem(item)
        self.horizontalLayout.addWidget(self.channel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.account_info = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.account_info.setFont(font)
        self.account_info.setStyleSheet("border: none")
        self.account_info.setReadOnly(True)
        self.account_info.setObjectName("account_info")
        self.horizontalLayout_3.addWidget(self.account_info)
        self.reconnect = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reconnect.setFont(font)
        self.reconnect.setStyleSheet("#reconnect {\n"
"    border: 1px solid #bf5af2;\n"
"    border-radius: .3em;\n"
"    padding: .2em .5em;\n"
"    min-width: 4em;\n"
"}\n"
"#reconnect:hover {\n"
"    background-color: #bf5af2;\n"
"    color: #fff;\n"
"    padding-left: 0;\n"
"}")
        self.reconnect.setObjectName("reconnect")
        self.horizontalLayout_3.addWidget(self.reconnect)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("#textEdit {\n"
"    background: #fafafa;\n"
"    border: none;\n"
"}")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.message = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.message.setFont(font)
        self.message.setStyleSheet("#message {\n"
"    background-color: #fafafa;\n"
"    border: 1px solid transparent;\n"
"    border-bottom-color: #ccc;\n"
"    padding: .2em;\n"
"    margin-bottom: 1px;\n"
"}\n"
"#message:focus {\n"
"    border-bottom-color: #64d2ff;\n"
"    border-width: 2px;\n"
"}")
        self.message.setObjectName("message")
        self.horizontalLayout_2.addWidget(self.message)
        self.upload = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.upload.setFont(font)
        self.upload.setStyleSheet("#upload {\n"
"    border: 1px solid #66d4cf;\n"
"    border-radius: .3em;\n"
"    padding: .2em .5em;\n"
"    min-width: 4em;\n"
"}\n"
"#upload:hover {\n"
"    background-color: #66d4cf;\n"
"    color: #fff;\n"
"    padding-left: 0;\n"
"}")
        self.upload.setObjectName("upload")
        self.horizontalLayout_2.addWidget(self.upload)
        self.send = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.send.setFont(font)
        self.send.setStyleSheet("#send {\n"
"    border: 1px solid #0a84ff;\n"
"    border-radius: .3em;\n"
"    padding: .2em .5em;\n"
"    min-width: 4em;\n"
"}\n"
"#send:hover {\n"
"    background-color: #0a84ff;\n"
"    color: #fff;\n"
"    padding-left: 0;\n"
"}")
        self.send.setObjectName("send")
        self.horizontalLayout_2.addWidget(self.send)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setStyleSheet("")
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionSettings_2 = QtGui.QAction(MainWindow)
        self.actionSettings_2.setObjectName("actionSettings_2")
        self.actionLogin = QtGui.QAction(MainWindow)
        self.actionLogin.setObjectName("actionLogin")
        self.actionLogout = QtGui.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionSwitch_user = QtGui.QAction(MainWindow)
        self.actionSwitch_user.setObjectName("actionSwitch_user")
        self.menuFile.addAction(self.actionLogin)
        self.menuFile.addAction(self.actionLogout)
        self.menuFile.addAction(self.actionSwitch_user)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QtChat"))
        __sortingEnabled = self.channel.isSortingEnabled()
        self.channel.setSortingEnabled(False)
        item = self.channel.item(0)
        item.setText(_translate("MainWindow", "Default Channel"))
        self.channel.setSortingEnabled(__sortingEnabled)
        self.account_info.setText(_translate("MainWindow", "Username (Channel 127.0.0.1: 8080)"))
        self.reconnect.setText(_translate("MainWindow", "Reconnect"))
        self.upload.setText(_translate("MainWindow", "Upload"))
        self.send.setText(_translate("MainWindow", "Send"))
        self.menuFile.setTitle(_translate("MainWindow", "Account"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionSettings_2.setText(_translate("MainWindow", "Settings"))
        self.actionLogin.setText(_translate("MainWindow", "Login"))
        self.actionLogout.setText(_translate("MainWindow", "Logout"))
        self.actionSwitch_user.setText(_translate("MainWindow", "Switch user"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
